package com.example.minimusic.ui.theme

import androidx.compose.ui.graphics.Color

// Warm neutral fallback palette for API < 31, where wallpaper-derived Monet
// colors are unavailable. Android 12+ uses the system dynamic scheme instead.
val AmberPrimaryLight = Color(0xFF8C5000)
val AmberOnPrimaryLight = Color(0xFFFFFFFF)
val AmberPrimaryContainerLight = Color(0xFFFFDDB3)
val AmberOnPrimaryContainerLight = Color(0xFF2C1600)
val AmberSecondaryLight = Color(0xFF6F5B40)
val AmberOnSecondaryLight = Color(0xFFFFFFFF)
val AmberSecondaryContainerLight = Color(0xFFF2E2C4)
val AmberOnSecondaryContainerLight = Color(0xFF241A08)
val AmberTertiaryLight = Color(0xFF7F5260)
val AmberOnTertiaryLight = Color(0xFFFFFFFF)
val AmberTertiaryContainerLight = Color(0xFFFFD9E1)
val AmberOnTertiaryContainerLight = Color(0xFF32111D)
val AmberBackgroundLight = Color(0xFFFFFBFF)
val AmberOnBackgroundLight = Color(0xFF201B16)
val AmberSurfaceLight = Color(0xFFFFFBFF)
val AmberOnSurfaceLight = Color(0xFF201B16)
val AmberSurfaceVariantLight = Color(0xFFF0E0C9)
val AmberOnSurfaceVariantLight = Color(0xFF504638)
val AmberOutlineLight = Color(0xFF817568)
val AmberOutlineVariantLight = Color(0xFFD4C4AF)
val AmberInverseSurfaceLight = Color(0xFF362F27)
val AmberInverseOnSurfaceLight = Color(0xFFFFEEE1)
val AmberInversePrimaryLight = Color(0xFFFFB876)

val AmberPrimaryDark = Color(0xFFFFB876)
val AmberOnPrimaryDark = Color(0xFF4A2900)
val AmberPrimaryContainerDark = Color(0xFF693C00)
val AmberOnPrimaryContainerDark = Color(0xFFFFDDB3)
val AmberSecondaryDark = Color(0xFFDDC3A2)
val AmberOnSecondaryDark = Color(0xFF3C2F1B)
val AmberSecondaryContainerDark = Color(0xFF554833)
val AmberOnSecondaryContainerDark = Color(0xFFF2E2C4)
val AmberTertiaryDark = Color(0xFFEFB8C8)
val AmberOnTertiaryDark = Color(0xFF4A2530)
val AmberTertiaryContainerDark = Color(0xFF633B48)
val AmberOnTertiaryContainerDark = Color(0xFFFFD9E1)
val AmberBackgroundDark = Color(0xFF1F1B16)
val AmberOnBackgroundDark = Color(0xFFEAE1D9)
val AmberSurfaceDark = Color(0xFF1F1B16)
val AmberOnSurfaceDark = Color(0xFFEAE1D9)
val AmberSurfaceVariantDark = Color(0xFF504638)
val AmberOnSurfaceVariantDark = Color(0xFFD4C4AF)
val AmberOutlineDark = Color(0xFF9C8F80)
val AmberOutlineVariantDark = Color(0xFF504638)
val AmberInverseSurfaceDark = Color(0xFFEAE1D9)
val AmberInverseOnSurfaceDark = Color(0xFF362F27)
val AmberInversePrimaryDark = Color(0xFF8C5000)
